version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: binayub_db
    restart: always
    environment:
      POSTGRES_USER: binayub_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: binayub_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - binayub_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binayub_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://binayub_user:${DB_PASSWORD}@postgres:5432/binayub_store?schema=public
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
      NEXT_PUBLIC_WHATSAPP_NUMBER: ${NEXT_PUBLIC_WHATSAPP_NUMBER}
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - binayub_network

volumes:
  postgres_data:

networks:
  binayub_network:
    driver: bridge
